# .env for environment variables
---
version: "3"
services:
  homer:
    image: b4bz/homer:22.02.2
    container_name: homer
    restart: always
    ports:
      - ${APP_HOMER_PORT}:${APP_HOMER_PORT}
    volumes:
      - ${APP_DATA_DIR}/homer:/www/assets
    environment:
      - INIT_ASSETS=0 # 1 is default
  matrix:
    image: matrixdotorg/synapse
    container_name: matrix
    restart: always
    ports:
      - ${APP_MATRIX_PORT}:${APP_MATRIX_PORT}
    volumes:
      - ${APP_DATA_DIR}/matrix:/data
  nextcloud_db:
    container_name: nextcloud_db
    image: mariadb
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW --innodb-file-per-table=1 --skip-innodb-read-only-compressed
    volumes:
      - ${APP_DATA_DIR}/nextcloud/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: <YOUR_GENERATED_PASSWORD>
      MYSQL_PASSWORD: <YOUR_GENERATED_PASSWORD>
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
  nextcloud:
    container_name: nextcloud
    image: lscr.io/linuxserver/nextcloud
    restart: always
    ports:
      - ${APP_NEXTCLOUD_PORT}:443
    links:
      - nextcloud_db
    volumes:
      - ${APP_DATA_DIR}/nextcloud/appdata:/config
      - ${APP_DATA_DIR}/nextcloud/data:/data
    environment:
      MYSQL_PASSWORD: <YOUR_GENERATED_PASSWORD>
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_HOST: nextcloud_db
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    ports:
      - ${APP_VAULTWARDEN_PORT}:${APP_VAULTWARDEN_PORT}
    restart: always
    user: 1000:1000
    environment:
      ROCKET_PORT: "${APP_VAULTWARDEN_PORT}"
    volumes:
      - ${APP_DATA_DIR}/vaultwarden/data:/data

# docker run -it --rm -v ${APP_DATA_DIR}/matrix:/data  -e SYNAPSE_SERVER_NAME=atemosta.com -e SYNAPSE_REPORT_STATS=yes matrixdotorg/synapse:latest generate
# sudo certbot --nginx -d matrix.atemosta.com
