version: "3.8"
services:
  # CLI: mongo 127.0.0.1:27017
  mongo-db:
    container_name: mongo-db
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=pass12345
      - MONGO_INITDB_DATABASE=feh
    networks:
      - mongo-compose-network
    ports:
      - '27017:27017'
    volumes:
      - mongodb-data:/data/db
  # UI: http://127.0.0.1:8081
  mongo-express:
    container_name: mongo-express
    image: mongo-express
    depends_on:
      - mongo-db
    networks:
      - mongo-compose-network
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo-db
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=pass12345
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin123
    ports:
      - '8081:8081'
    volumes:
      - mongodb-data
volumes:
  mongodb-data:
    name: mongodb-data
networks:
  mongo-compose-network:
    driver: bridge