---
# Homepage configuration
# See https://fontawesome.com/v5/search for icons options

title: "Welcome to the World of Blades"
subtitle: "Forest House RP3"
logo: "assets/icons/icon-any.png"
# logo: "fas fa-swords"
# icon: "fas fa-swords"
# icon: "fas fa-skull-crossbones" # Optional icon

header: true
footer: '<p>Created with <span class="has-text-danger">❤️</span> with <a href="https://bulma.io/">bulma</a>, <a href="https://vuejs.org/">vuejs</a> & <a href="https://fontawesome.com/">font awesome</a> // Fork me on <a href="https://github.com/bastienwirtz/homer"><i class="fab fa-github-alt"></i></a></p>' # set false if you want to hide it.

# Optional theme customization
theme: default
colors:
  light:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#f5f5f5"
    card-background: "#ffffff"
    text: "#363636"
    text-header: "#ffffff"
    text-title: "#303030"
    text-subtitle: "#424242"
    card-shadow: rgba(0, 0, 0, 0.1)
    link: "#3273dc"
    link-hover: "#363636"
  dark:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#131313"
    card-background: "#2b2b2b"
    text: "#eaeaea"
    text-header: "#ffffff"
    text-title: "#fafafa"
    text-subtitle: "#f5f5f5"
    card-shadow: rgba(0, 0, 0, 0.4)
    link: "#3273dc"
    link-hover: "#ffdd57"

# Optional message
# message:
#   #url: https://b4bz.io
#   style: "is-dark" # See https://bulma.io/documentation/components/message/#colors for styling options.
#   title: "Demo !"
#   icon: "fa fa-grin"
#   content: "This is a dummy homepage demo. <br /> Find more information on <a href='https://github.com/bastienwirtz/homer'>github.com/bastienwirtz/homer</a>"

# Optional navbar
# links: [] # Allows for navbar (dark mode, layout, and search) without any links
# links:
#   - name: "Contribute"
#     icon: "fab fa-github"
#     url: "https://github.com/bastienwirtz/homer"
#     target: "_blank" # optional html a tag target attribute
#   - name: "Wiki"
#     icon: "fas fa-book"
#     url: "https://www.wikipedia.org/"
#   # this will link to a second homer page that will load config from additional-page.yml and keep default config values as in config.yml file
#   # see url field and assets/additional-page.yml.dist used in this example:
#   - name: "another page!"
#     icon: "fas fa-file-alt"
#     url: "#additional-page" 

# Services
# First level array represent a group.
# Leave only a "items" key if not using group (group name, icon & tagstyle are optional, section separation will not be displayed).
services:
  - name: "Applications"
    icon: "fas fa-cloud"
    items:
      # - name: "Element"
      #   logo: "assets/tools/sample.png"
      #   subtitle: "A glossy Matrix collaboration client for the web."
      #   tag: "app"
      #   url: "http://localhost:8088"
      - name: "Nextcloud"
        logo: "assets/tools/nextcloud.svg"
        subtitle: "Cloud Storage"
        url: "http://umbrel.local:8081/login"
      - name: "PhotoPrism"
        logo: "assets/tools/photoprism.svg"
        subtitle: "Photo Library"
        url: "http://umbrel.local:8087/login"
      - name: "Pi-hole"
        logo: "assets/tools/pi-hole.svg"
        subtitle: "DNS Sinkhole"
        url: "http://umbrellocal:8082/admin"
      - name: "SimpleTorrent"
        logo: "assets/tools/simpletorrent.svg"
        subtitle: "Paying for stuff KEKW"
        url: "http://umbrel.local:8086/"
      # - name: "Synapse"
      #   logo: "assets/tools/sample.png"
      #   subtitle: "Matrix homeserver written in Python 3/Twisted."
      #   tag: "app"
      #   url: "http://localhost:8008"
      - name: "Umbrel"
        logo: "assets/tools/umbrel.png"
        subtitle: "BITCONNECTTTTTT"
        url: "http://umbrel.local"
      - name: "Uptime Kuma"
        logo: "assets/tools/uptime-kuma.svg"
        subtitle: "Application Monitoring"
        url: "http://umbrel.local:8385"
      - name: "Vaultwarden"
        logo: "assets/tools/vaultwarden.svg"
        subtitle: "Password Manager"
        url: "http://ForestHouseRP4.local:8089"
  - name: "Communities"
    icon: "fas fa-cloud"
    items:
      - name: "Discord (Litwooto)"
        logo: "assets/tools/discord.png"
        subtitle: "Get Deceived by Oscar's Lies"
        url: "https://discord.com/channels/663550615632216088/663550616299241504"
      - name: "Discord (FEH-Gauntlet-Bot)"
        logo: "assets/tools/discord.png"
        subtitle: "Edelgard did nothing wrong"
        url: "https://discord.com/channels/781530856065728533/781530856065728536"
      - name: "Element (Atemosta)"
        logo: "assets/tools/element.svg"
        subtitle: "Discord but not cringe"
        url: "http://umbrel.local:8088/"
      - name: "GitHub (Ousikai)"
        logo: "assets/tools/github.png"
        subtitle: "Writer's Retreat"
        url: "https://github.com/ousikai"
      - name: "GitHub (OscarKevinXR)"
        logo: "assets/tools/github.png"
        subtitle: "Bridging Imperfect Realities"
        url: "https://github.com/oscarkevinxr"
      - name: "Twitch (Ousikai)"
        logo: "assets/tools/github.png"
        subtitle: "Waste my time 2022"
        url: "https://www.twitch.tv/ousikai"
  - name: "Enterprise"
    icon: "fas fa-cloud"
    items:
      - name: "BTCMempool"
        logo: "assets/tools/mempool.svg"
        subtitle: "BTC Blockchain Explorer"
        url: "http://umbrel.local:3006"
      - name: "BTCPay"
        logo: "assets/tools/btcpay.svg"
        subtitle: "Bitcoin Store"
        url: "http://umbrel.local:3003/login?ReturnUrl=%2F"
      - name: "Gitea"
        logo: "assets/tools/gitea.svg"
        subtitle: "Git Repository"
        url: "http://umbrel.local:8085"
      - name: "Matrix Synapse (Atemosta)"
        logo: "assets/tools/matrix.svg"
        subtitle: "Discord but not cringe"
        url: "http://umbrel.local:8088/"